#!/bin/bash
if [ "$1" != "" ];
then
    DUMP="$DB_NAME.dump"
    TEMPDUMPFILE="/bugzilla/tmp_$DUMP"
    DUMPFILE="/bugzilla/$DUMP"
    TEMPTILE="/bugzilla/backups/tmp_$1.tar.gz"
    FILE="/bugzilla/backups/$1.tar.gz"

    mysqldump --max-allowed-packet=32M --user="$DB_USER_NAME" --password="$DB_USER_PASSWORD" "$DB_NAME" > $TEMPDUMPFILE
    mv $TEMPDUMPFILE $DUMPFILE

    cd /bugzilla
    tar -czf $TEMPTILE $DUMP data
    mv $TEMPTILE $FILE

    rm $DUMPFILE
fi
