#!/bin/bash
if [ "$1" != "" ];
then
    DUMP="bugs.dump"
    TEMPDUMPFILE="/bugzilla/tmp_$DUMP"
    DUMPFILE="/bugzilla/$DUMP"
    TEMPTILE="/bugzilla/backups/tmp_$1.tar.gz"
    FILE="/bugzilla/backups/$1.tar.gz"

    mysqldump --max-allowed-packet=32M --user="bugs" --password="$DB_USER_PASSWORD" "bugs" > $TEMPDUMPFILE
    mv $TEMPDUMPFILE $DUMPFILE

    cd /bugzilla
    tar -czf $TEMPTILE db data $DUMP
    mv $TEMPTILE $FILE

    rm $DUMPFILE
fi
