#!/bin/bash
if [ ! -d /bugzilla/db/mysql ];
then
    mysql_install_db
fi

sed -i "s|\$db_pass.*|\$db_pass = '"$DB_USER_PASSWORD"';|" /var/www/html/bugzilla/localconfig

trap /bugzilla/scripts/containerShutdown HUP SIGHUP INT SIGINT QUIT SIGQUIT TERM SIGTERM

source /bugzilla/scripts/containerConfig
$startDbCmd & $startWebCmd & $startDummyCmd
eval $waitDummyCmd
