#!/bin/bash
/var/www/html/$GUEST_APP_NAME/checksetup.pl
if [ $? -ne 0 ];
then
    exit 1
fi
mysql --user=root --password="$DB_ROOT_PASSWORD" -e "USE bugs; ALTER TABLE attachments AVG_ROW_LENGTH=1000000, MAX_ROWS=20000;"
