#!/bin/bash
if [ ! -d /bugzilla/db/mysql ];
then
    mysql_install_db
fi

sed -i "s|\$db_pass.*|\$db_pass = '"$DB_USER_PASSWORD"';|" /var/www/html/bugzilla/localconfig

trap /bugzilla/scripts/shutdown SIGHUP SIGINT SIGTERM TERM

mysqld & apache2ctl -D FOREGROUND & wait
