#!/bin/bash
if [ ! -d /bugzilla/database/mysql ];
then
    mysql_install_db
fi

sed -i "s|\$db_pass.*|\$db_pass = '"$DB_USER_PASSWORD"';|" /var/www/html/${GUEST_APP_NAME}/localconfig

trap /bugzilla/shutdown TERM

mysqld &
/usr/sbin/apache2ctl -D FOREGROUND
