#!/bin/bash
if [ ! -d /bugzilla/db/mysql ];
then
    mysqld --initialize-insecure
fi

sed -i "s|\$db_pass.*|\$db_pass = '"$DB_USER_PASSWORD"';|" /var/www/html/bugzilla/localconfig

trap /bugzilla/scripts/shutdown SIGHUP SIGINT SIGTERM TERM

startMySQLCmd="mysqld"
startApacheCmd="apache2ctl -D FOREGROUND"
$startMySQLCmd & $startApacheCmd & wait
