#!/bin/bash
if [ "$1" != "" ];
then
    DUMP="$DB_NAME.dump"
    DUMPFILE="/bugzilla/$DUMP"
    FILE="/bugzilla/backups/$1.tar.gz"
    source /bugzilla/scripts/containerConfig

    if [ -e "$FILE" ];
    then
        $stopWebCmd

        cd /bugzilla
        tar -xzf $FILE $DUMP data

        mysql --user="$DB_USER_NAME" --password="$DB_USER_PASSWORD" "$DB_NAME" < $DUMPFILE

        rm $DUMPFILE

        $startWebCmd
    fi
fi
